"""Add full_name, referred_by, and discount to User model

Revision ID: 2631caf5f012
Revises: 34fdb16efda4
Create Date: 2025-10-19 17:34:08.604252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2631caf5f012'
down_revision = '34fdb16efda4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('referred_by', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('discount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('discount')
        batch_op.drop_column('referred_by')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
