"""Add enrollment_id to Payment model

Revision ID: 66cfe3c63679
Revises: 2631caf5f012
Create Date: 2025-10-22 00:49:18.410913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66cfe3c63679'
down_revision = '2631caf5f012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrollment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_payment_enrollment_id', 'enrollment', ['enrollment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('enrollment_id')

    # ### end Alembic commands ###
