"""Add status column to enrollment

Revision ID: deb33522c68f
Revises: 
Create Date: 2025-10-15 21:15:24.373886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deb33522c68f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True, default='active'))

    # Update existing rows to have 'active' status
    op.execute("UPDATE enrollment SET status = 'active' WHERE status IS NULL")

    # Now make it NOT NULL
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.alter_column('status', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
